### ISSUE TITLE
problem about EDGE

### ISSUE THREAD

**Issue by xgt1986627** [jdstorey/edge#15]
I found the results of differential expression analyses were different for the same data set, even for the test data set existed in the package. I have tried the old 1.X version and the latest version and both had this problem. The number of significant gene is different every time and I didn't know which result should be used.

Thank you very much for your help!

**Comment by ajbass** [comment]
The ODP generates an empirical null to calculate p-values. If there's a lot of variability, I recommend setting the `bs.its` argument to be large and to set a seed (in order to reproduce result), e.g.,

```
odp(de_obj, bs.its = 1000, seed = 12345)
```

**Comment by xgt1986627** [comment]
Thank you very much, would you know how to do this in the earlier version 1.1.291, a point-and-click version

**Comment by ajbass** [comment]
I recommend using the latest version, as the point-and-click version is no longer updated.

**Comment by xgt1986627** [comment]
Thanks. But I am not very familiar with the command line way in the latest version, and I only use the function of time course experiment of differential expression analysis for significant genes. This function had been used in many publications in the earlier version like 1.1.291.  I tried to typed your command in the version 1.1.291 and failed.  So I want to know if there is any way to carry out such operation as you suggested. This version has been attached. Thank you very much for your help!

**Comment by xgt1986627** [comment]
I find the test data "endotoxin" also have different  results in every run in the earlier and the latest version. You are from the lab of author and you are professional.  Do you know how to deal with this problem before?

**Comment by xgt1986627** [comment]
I am sorry to disturb so much, but I still have a question about EDGE. Some one said the latest version is not suitable for the short term time course study like only three points existed. That is also one of the reason I choose the earlier version. My data just have three points and they are not time points, which is more fit for the "independent time course experiment".  Previously I thought the earlier version can hold such task because this function existed in the beginning.Do you think which version is better?
Thanks very much for all your kindly help!!

**Comment by xgt1986627** [comment]
I would like to know the whether the update of the latest version hadl change the results of significant different results than the point-and-click version?
