### ISSUE TITLE
problem about EDGE export

### ISSUE THREAD

**Issue by xgt1986627** [jdstorey/edge#16]
after this step
sig_results <- qvalueObj(de_odp)
how can I export the list?
I find the ID or gene name can not export with others like qvalues by using write.table.
the result showed
"Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ‘"call"’ to a data.frame"
thanks very much for help!

**Comment by ajbass** [comment]
You have to load the qvalue package:

```
library(qvalue)
write.qvalue(sig_results, file = "temp")
# or
qvalue::write.qvalue(sig_results, file = "temp")

**Comment by xgt1986627** [comment]
but the results still don't have ID or gene name. Only q-value how to know which possess which?
