### ISSUE TITLE
Q-value and local FDR

### ISSUE THREAD

**Issue by xgt1986627** [jdstorey/edge#17]
In the early version, there isn't local FDR showed in the result page. But in the latest version,  local FDR appeared and the value of it is not the same with q-value. I found their meaning are the same in publication. Why they are different in latest EDGE and which should I use to judge whether the gene or protein is significant?

**Comment by ajbass** [comment]
The old EDGE package is no longer maintained. See http://genomine.org/papers/Storey_FDR_2011.pdf for more on the q-value/local false discovery rate.
