### ISSUE TITLE
static experiment

### ISSUE THREAD

**Issue by xgt1986627** [jdstorey/edge#19]
Hello, I would like to know in the multiple  groups comparisons in static experiment (more than 2 groups), is the results means their existed significant difference within these several groups? Then the difference of every two groups isn't analysed, is it?
I want to know whether is it like the one way ANOVA , and it needs to do post-hoc test like Tukey’s honestly significant difference (THSD) in ANOVA? 
If yes, how to do post-hoc test in EDGE?
Thanks very much for your help!

**Comment by jdstorey** [comment]
This type of question is better suited for https://support.bioconductor.org.
