### ISSUE TITLE
StoreyLab/edge installation issue

### ISSUE THREAD

**Issue by Hanuphant** [jdstorey/edge#23]
The dependency package 'jackstraw' is not available and due to that I can't install and load edge package. Where can I get the "jackstraw"?
Using latest R 4.1.0, BiocManager 3.13.1

The following errors I see when I try to load edge
`library(edge)`

>

> Loading required package: Biobase
> Loading required package: BiocGenerics
> Loading required package: parallel
> 
> Attaching package: 'BiocGenerics'
> 
> The following objects are masked from 'package:parallel':
> 
>     clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
>     clusterExport, clusterMap, parApply, parCapply, parLapply,
>     parLapplyLB, parRapply, parSapply, parSapplyLB
> 
> The following objects are masked from 'package:stats':
> 
>     IQR, mad, sd, var, xtabs
> 
> The following objects are masked from 'package:base':
> 
>     anyDuplicated, append, as.data.frame, basename, cbind, colnames,
>     dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
>     grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
>     order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
>     rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
>     union, unique, unsplit, which.max, which.min
> 
> Welcome to Bioconductor
> 
>     Vignettes contain introductory material; view with
>     'browseVignettes()'. To cite Bioconductor, see
>     'citation("Biobase")', and for packages 'citation("pkgname")'.
> 
> Error: package or namespace load failed for 'edge' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck =
> vI[[i]]):
>  there is no package called 'jackstraw'

I hope someone can guide me through this.

**Comment by Hanuphant** [comment]
Installed ncchung/jackstraw and StoreyLab/alstructure with force = TRUE parameter and the package loaded without any issue.

**Comment by ncchung** [comment]
FYI, the jackstraw package was dropped from CRAN temporarily because of an upcoming R 4.2 update. I'll submit a new version of the jackstraw asap. 
In meanwhile, please install the latest version from Github: https://github.com/ncchung/jackstraw
